const FPS = 60;
const RUNNING_SECONDS = 10;
const RUNWAYS_LENGTH = 5632;

const ONE_FRAME = 1000 / FPS;
const MILEAGE_PER_SECOND = RUNWAYS_LENGTH / RUNNING_SECONDS;
const MILEAGE_PER_FAME = MILEAGE_PER_SECOND / FPS;
